
=== Ciclo 1/5 | Hora 8:00 ===
→ Coletando ofertas...
→ Gerando imagens...
→ Enviando via WhatsApp...
🟢 Envio concluído. Log:
 {'stdout': '', 'stderr': '', 'returncode': -15}
🛑 Encerrando whatsapp.py (PID 23422)
🕒 Aguardando 1 hora até próximo envio...
⏳ Aguardando 2m 00s...⏳ Aguardando 1m 30s...⏳ Aguardando 1m 00s...⏳ Aguardando 0m 30s...
⏱️ Próximo ciclo iniciado.


=== Ciclo 2/5 | Hora 9:00 ===
→ Coletando ofertas...
→ Gerando imagens...
→ Enviando via WhatsApp...
🟢 Envio concluído. Log:
 {'stdout': "🟡 Aguardando WhatsApp Web carregar...\n✅ Grupo encontrado rapidamente.\n\n📤 Tentando enviar anúncio (1/3): anuncio_6.txt\n✅ Preview detectado, enviando mensagem...\n✅ Arquivo movido para '/home/linuxlite/Github/bot-shoppe/dados/imagem_enviadas'.\n⏳ Aguardando 30 segundos antes do próximo envio...\n\n📤 Tentando enviar anúncio (2/3): anuncio_20.txt\n⛔ Preview não carregado. Apagando e pulando...\n❌ Falha ao enviar. Pulando para o próximo arquivo.\n⏳ Aguardando 30 segundos antes do próximo envio...\n\n📤 Tentando enviar anúncio (2/3): anuncio_10.txt\n⛔ Preview não carregado. Apagando e pulando...\n❌ Falha ao enviar. Pulando para o próximo arquivo.\n⏳ Aguardando 30 segundos antes do próximo envio...\n\n📤 Tentando enviar anúncio (2/3): anuncio_11.txt\n✅ Preview detectado, enviando mensagem...\n", 'stderr': 'Traceback (most recent call last):\n  File "/home/linuxlite/Github/bot-shoppe/whatsapp.py", line 142, in <module>\n    main()\n  File "/home/linuxlite/Github/bot-shoppe/whatsapp.py", line 128, in main\n    os.rename(caminho, novo_caminho)\nFileNotFoundError: [Errno 2] No such file or directory: \'/home/linuxlite/Github/bot-shoppe/dados/imagem/anuncio_11.txt\' -> \'/home/linuxlite/Github/bot-shoppe/dados/imagem_enviadas/anuncio_11.txt\'\n', 'returncode': 1}
🛑 Encerrando whatsapp.py (PID 24099)
🕒 Aguardando 1 hora até próximo envio...
⏳ Aguardando 2m 00s...⏳ Aguardando 1m 30s...⏳ Aguardando 1m 00s...⏳ Aguardando 0m 30s...
⏱️ Próximo ciclo iniciado.


=== Ciclo 3/5 | Hora 10:00 ===
→ Coletando ofertas...
→ Gerando imagens...
→ Enviando via WhatsApp...
🟢 Envio concluído. Log:
 {'stdout': '', 'stderr': '', 'returncode': -15}
🛑 Encerrando whatsapp.py (PID 25545)
🕒 Aguardando 1 hora até próximo envio...
⏳ Aguardando 2m 00s...⏳ Aguardando 1m 30s...⏳ Aguardando 1m 00s...⏳ Aguardando 0m 30s...
⏱️ Próximo ciclo iniciado.


=== Ciclo 4/5 | Hora 11:00 ===
→ Coletando ofertas...
→ Gerando imagens...
→ Enviando via WhatsApp...
🟢 Envio concluído. Log:
 {'stdout': '', 'stderr': 'Traceback (most recent call last):\n  File "/home/linuxlite/Github/bot-shoppe/whatsapp.py", line 142, in <module>\n    main()\n  File "/home/linuxlite/Github/bot-shoppe/whatsapp.py", line 107, in main\n    driver = iniciar_whatsapp()\n             ^^^^^^^^^^^^^^^^^^\n  File "/home/linuxlite/Github/bot-shoppe/whatsapp.py", line 23, in iniciar_whatsapp\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__\n    super().__init__(\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 261, in __init__\n    self.start_session(capabilities)\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 362, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)["value"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in execute\n    self.error_handler.check_response(response)\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don\'t use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nStacktrace:\n#0 0x5c0cd139f87a <unknown>\n#1 0x5c0cd0e442e0 <unknown>\n#2 0x5c0cd0e7e7bd <unknown>\n#3 0x5c0cd0e79ad7 <unknown>\n#4 0x5c0cd0ec9e9e <unknown>\n#5 0x5c0cd0ec9466 <unknown>\n#6 0x5c0cd0ebb683 <unknown>\n#7 0x5c0cd0e87b5b <unknown>\n#8 0x5c0cd0e88f31 <unknown>\n#9 0x5c0cd13647cb <unknown>\n#10 0x5c0cd13685d4 <unknown>\n#11 0x5c0cd134b2c9 <unknown>\n#12 0x5c0cd1369178 <unknown>\n#13 0x5c0cd132f6bf <unknown>\n#14 0x5c0cd138ce78 <unknown>\n#15 0x5c0cd138d056 <unknown>\n#16 0x5c0cd139eb96 <unknown>\n#17 0x76c39a69caa4 <unknown>\n#18 0x76c39a729c3c <unknown>\n\n', 'returncode': 1}
🕒 Aguardando 1 hora até próximo envio...
⏳ Aguardando 2m 00s...⏳ Aguardando 1m 30s...⏳ Aguardando 1m 00s...⏳ Aguardando 0m 30s...
⏱️ Próximo ciclo iniciado.


=== Ciclo 5/5 | Hora 12:00 ===
→ Coletando ofertas...
→ Gerando imagens...
→ Enviando via WhatsApp...
🟢 Envio concluído. Log:
 {'stdout': '', 'stderr': 'Traceback (most recent call last):\n  File "/home/linuxlite/Github/bot-shoppe/whatsapp.py", line 142, in <module>\n    main()\n  File "/home/linuxlite/Github/bot-shoppe/whatsapp.py", line 107, in main\n    driver = iniciar_whatsapp()\n             ^^^^^^^^^^^^^^^^^^\n  File "/home/linuxlite/Github/bot-shoppe/whatsapp.py", line 23, in iniciar_whatsapp\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__\n    super().__init__(\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 261, in __init__\n    self.start_session(capabilities)\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 362, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)["value"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in execute\n    self.error_handler.check_response(response)\n  File "/home/linuxlite/Github/bot-shoppe/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don\'t use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nStacktrace:\n#0 0x571e44b1087a <unknown>\n#1 0x571e445b52e0 <unknown>\n#2 0x571e445ef7bd <unknown>\n#3 0x571e445eaad7 <unknown>\n#4 0x571e4463ae9e <unknown>\n#5 0x571e4463a466 <unknown>\n#6 0x571e4462c683 <unknown>\n#7 0x571e445f8b5b <unknown>\n#8 0x571e445f9f31 <unknown>\n#9 0x571e44ad57cb <unknown>\n#10 0x571e44ad95d4 <unknown>\n#11 0x571e44abc2c9 <unknown>\n#12 0x571e44ada178 <unknown>\n#13 0x571e44aa06bf <unknown>\n#14 0x571e44afde78 <unknown>\n#15 0x571e44afe056 <unknown>\n#16 0x571e44b0fb96 <unknown>\n#17 0x74471029caa4 <unknown>\n#18 0x744710329c3c <unknown>\n\n', 'returncode': 1}
